server:
  port: 9000
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful

gateway-uri: http://localhost:${server.port}
spa-uri: http://localhost:3000
issuer-uri: http://localhost:8080
post-logout-redirect-uri: ${gateway-uri}/

#pre-authorization-status: NO_CONTENT
#post-authorization-status: NO_CONTENT

spring:
  application:
    name: edge-service
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000 # 2s
        response-timeout: 5s
        pool:
          type: elastic
          max-idle-time: 15s
          max-life-time: 60s
      routes:
        #        - id: customer-route
        #          uri: ${CUSTOMER_SERVICE_URL:http://localhost:9001}
        #          predicates:
        #            - Path=/api/customers/**
        #          filters:
        #            - RewritePath=/api/(?<segment>.*), /$\{segment}
        #            - TokenRelay=
        - id: spa
          uri: ${spa-uri}
          predicates:
            - Path=/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Access-Control-Request-Headers
        - SaveSession
  #  data:
  #    redis:
  #      connect-timeout: 2s
  #      host: localhost
  #      port: 6379
  #      timeout: 1s
  #  session:
  #    timeout: 10m
  #    redis:
  #      namespace: ecomart:edge
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: edge-service
            client-secret: ecomart-keycloak-secret
            authorization-grant-type: authorization_code
            scope: openid,roles,profile,email,offline_access
        provider:
          keycloak:
            issuer-uri: ${issuer-uri}/realms/Ecomart

logging:
  level:
    org:
      springframework:
        security: INFO
        boot: INFO
