server:
  port: 9000
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  reactive:
    session:
      cookie:
        name: SESSION_${spring.application.name}
  shutdown: graceful

gateway-uri: http://localhost:${server.port}
spa-uri: http://localhost:3000
issuer-uri: http://localhost:8080/realms/Ecomart
post-logout-redirect-uri: ${gateway-uri}/
api-version: v1

#pre-authorization-status: NO_CONTENT
#post-authorization-status: NO_CONTENT

spring:
  application:
    name: edge-service
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000 # 2s
        response-timeout: 5s
        pool:
          type: elastic
          max-idle-time: 15s
          max-life-time: 60s
      routes:
#                - id: customer-route
#                  uri: ${CUSTOMER_SERVICE_URL:http://localhost:9001}
#                  predicates:
#                    - Path=/api/customers/**
#                  filters:
#                    - RewritePath=/api/(?<segment>.*), /$\{segment}
#                    - TokenRelay=
        - id: product-route
          uri: ${PRODUCT_SERVICE_URL:http://localhost:9002}
          predicates:
            - Path=/api/${api-version}/product_service/**
          filters:
            - RewritePath=/api/${api-version}/product_service/(?<segment>.*), /$\{segment}
        - id: spa
          uri: ${spa-uri}
          predicates:
            - Path=/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Access-Control-Request-Headers
        - SaveSession
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s
  session:
    timeout: 14d
    redis:
      namespace: ecomart:edge
  security:
    oauth2:
      client:
        registration:
          edge-service-keycloak:
            provider: keycloak
            client-id: edge-service
            client-secret: ecomart-keycloak-secret
            authorization-grant-type: authorization_code
            scope: openid,roles,profile,email,offline_access
#          ecomart-mobile: # TODO: Add a mobile oauth2 client
#            provider: keycloak
#            client-id: ecomart-mobile
#            client-secret: ""
#            authorization-grant-type: authorization_code
#            scope: openid,roles,profile,email,offline_access
        provider:
          keycloak:
            issuer-uri: ${issuer-uri}

logging:
  level:
    org:
      springframework:
        security: DEBUG
        boot: INFO
        session: DEBUG
        web.server.session: DEBUG
