/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.project.young.kafka.product.avro.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ProductCatalogChangedAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4607678151797103051L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProductCatalogChangedAvroModel\",\"namespace\":\"com.project.young.kafka.product.avro.model\",\"fields\":[{\"name\":\"eventId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"productId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"categoryId\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"changeType\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"occurredAt\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ProductCatalogChangedAvroModel> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ProductCatalogChangedAvroModel> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ProductCatalogChangedAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ProductCatalogChangedAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ProductCatalogChangedAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ProductCatalogChangedAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ProductCatalogChangedAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ProductCatalogChangedAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ProductCatalogChangedAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String eventId;
  private java.lang.String productId;
  private java.lang.Long categoryId;
  private java.lang.String changeType;
  private long occurredAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ProductCatalogChangedAvroModel() {}

  /**
   * All-args constructor.
   * @param eventId The new value for eventId
   * @param productId The new value for productId
   * @param categoryId The new value for categoryId
   * @param changeType The new value for changeType
   * @param occurredAt The new value for occurredAt
   */
  public ProductCatalogChangedAvroModel(java.lang.String eventId, java.lang.String productId, java.lang.Long categoryId, java.lang.String changeType, java.lang.Long occurredAt) {
    this.eventId = eventId;
    this.productId = productId;
    this.categoryId = categoryId;
    this.changeType = changeType;
    this.occurredAt = occurredAt;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return eventId;
    case 1: return productId;
    case 2: return categoryId;
    case 3: return changeType;
    case 4: return occurredAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: eventId = value$ != null ? value$.toString() : null; break;
    case 1: productId = value$ != null ? value$.toString() : null; break;
    case 2: categoryId = (java.lang.Long)value$; break;
    case 3: changeType = value$ != null ? value$.toString() : null; break;
    case 4: occurredAt = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'eventId' field.
   * @return The value of the 'eventId' field.
   */
  public java.lang.String getEventId() {
    return eventId;
  }


  /**
   * Sets the value of the 'eventId' field.
   * @param value the value to set.
   */
  public void setEventId(java.lang.String value) {
    this.eventId = value;
  }

  /**
   * Gets the value of the 'productId' field.
   * @return The value of the 'productId' field.
   */
  public java.lang.String getProductId() {
    return productId;
  }


  /**
   * Sets the value of the 'productId' field.
   * @param value the value to set.
   */
  public void setProductId(java.lang.String value) {
    this.productId = value;
  }

  /**
   * Gets the value of the 'categoryId' field.
   * @return The value of the 'categoryId' field.
   */
  public java.lang.Long getCategoryId() {
    return categoryId;
  }


  /**
   * Sets the value of the 'categoryId' field.
   * @param value the value to set.
   */
  public void setCategoryId(java.lang.Long value) {
    this.categoryId = value;
  }

  /**
   * Gets the value of the 'changeType' field.
   * @return The value of the 'changeType' field.
   */
  public java.lang.String getChangeType() {
    return changeType;
  }


  /**
   * Sets the value of the 'changeType' field.
   * @param value the value to set.
   */
  public void setChangeType(java.lang.String value) {
    this.changeType = value;
  }

  /**
   * Gets the value of the 'occurredAt' field.
   * @return The value of the 'occurredAt' field.
   */
  public long getOccurredAt() {
    return occurredAt;
  }


  /**
   * Sets the value of the 'occurredAt' field.
   * @param value the value to set.
   */
  public void setOccurredAt(long value) {
    this.occurredAt = value;
  }

  /**
   * Creates a new ProductCatalogChangedAvroModel RecordBuilder.
   * @return A new ProductCatalogChangedAvroModel RecordBuilder
   */
  public static com.project.young.kafka.product.avro.model.ProductCatalogChangedAvroModel.Builder newBuilder() {
    return new com.project.young.kafka.product.avro.model.ProductCatalogChangedAvroModel.Builder();
  }

  /**
   * Creates a new ProductCatalogChangedAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ProductCatalogChangedAvroModel RecordBuilder
   */
  public static com.project.young.kafka.product.avro.model.ProductCatalogChangedAvroModel.Builder newBuilder(com.project.young.kafka.product.avro.model.ProductCatalogChangedAvroModel.Builder other) {
    if (other == null) {
      return new com.project.young.kafka.product.avro.model.ProductCatalogChangedAvroModel.Builder();
    } else {
      return new com.project.young.kafka.product.avro.model.ProductCatalogChangedAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new ProductCatalogChangedAvroModel RecordBuilder by copying an existing ProductCatalogChangedAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new ProductCatalogChangedAvroModel RecordBuilder
   */
  public static com.project.young.kafka.product.avro.model.ProductCatalogChangedAvroModel.Builder newBuilder(com.project.young.kafka.product.avro.model.ProductCatalogChangedAvroModel other) {
    if (other == null) {
      return new com.project.young.kafka.product.avro.model.ProductCatalogChangedAvroModel.Builder();
    } else {
      return new com.project.young.kafka.product.avro.model.ProductCatalogChangedAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for ProductCatalogChangedAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProductCatalogChangedAvroModel>
    implements org.apache.avro.data.RecordBuilder<ProductCatalogChangedAvroModel> {

    private java.lang.String eventId;
    private java.lang.String productId;
    private java.lang.Long categoryId;
    private java.lang.String changeType;
    private long occurredAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.project.young.kafka.product.avro.model.ProductCatalogChangedAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.productId)) {
        this.productId = data().deepCopy(fields()[1].schema(), other.productId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.categoryId)) {
        this.categoryId = data().deepCopy(fields()[2].schema(), other.categoryId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.changeType)) {
        this.changeType = data().deepCopy(fields()[3].schema(), other.changeType);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.occurredAt)) {
        this.occurredAt = data().deepCopy(fields()[4].schema(), other.occurredAt);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing ProductCatalogChangedAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.project.young.kafka.product.avro.model.ProductCatalogChangedAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.productId)) {
        this.productId = data().deepCopy(fields()[1].schema(), other.productId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.categoryId)) {
        this.categoryId = data().deepCopy(fields()[2].schema(), other.categoryId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.changeType)) {
        this.changeType = data().deepCopy(fields()[3].schema(), other.changeType);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.occurredAt)) {
        this.occurredAt = data().deepCopy(fields()[4].schema(), other.occurredAt);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'eventId' field.
      * @return The value.
      */
    public java.lang.String getEventId() {
      return eventId;
    }


    /**
      * Sets the value of the 'eventId' field.
      * @param value The value of 'eventId'.
      * @return This builder.
      */
    public com.project.young.kafka.product.avro.model.ProductCatalogChangedAvroModel.Builder setEventId(java.lang.String value) {
      validate(fields()[0], value);
      this.eventId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'eventId' field has been set.
      * @return True if the 'eventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'eventId' field.
      * @return This builder.
      */
    public com.project.young.kafka.product.avro.model.ProductCatalogChangedAvroModel.Builder clearEventId() {
      eventId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'productId' field.
      * @return The value.
      */
    public java.lang.String getProductId() {
      return productId;
    }


    /**
      * Sets the value of the 'productId' field.
      * @param value The value of 'productId'.
      * @return This builder.
      */
    public com.project.young.kafka.product.avro.model.ProductCatalogChangedAvroModel.Builder setProductId(java.lang.String value) {
      validate(fields()[1], value);
      this.productId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'productId' field has been set.
      * @return True if the 'productId' field has been set, false otherwise.
      */
    public boolean hasProductId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'productId' field.
      * @return This builder.
      */
    public com.project.young.kafka.product.avro.model.ProductCatalogChangedAvroModel.Builder clearProductId() {
      productId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'categoryId' field.
      * @return The value.
      */
    public java.lang.Long getCategoryId() {
      return categoryId;
    }


    /**
      * Sets the value of the 'categoryId' field.
      * @param value The value of 'categoryId'.
      * @return This builder.
      */
    public com.project.young.kafka.product.avro.model.ProductCatalogChangedAvroModel.Builder setCategoryId(java.lang.Long value) {
      validate(fields()[2], value);
      this.categoryId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'categoryId' field has been set.
      * @return True if the 'categoryId' field has been set, false otherwise.
      */
    public boolean hasCategoryId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'categoryId' field.
      * @return This builder.
      */
    public com.project.young.kafka.product.avro.model.ProductCatalogChangedAvroModel.Builder clearCategoryId() {
      categoryId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'changeType' field.
      * @return The value.
      */
    public java.lang.String getChangeType() {
      return changeType;
    }


    /**
      * Sets the value of the 'changeType' field.
      * @param value The value of 'changeType'.
      * @return This builder.
      */
    public com.project.young.kafka.product.avro.model.ProductCatalogChangedAvroModel.Builder setChangeType(java.lang.String value) {
      validate(fields()[3], value);
      this.changeType = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'changeType' field has been set.
      * @return True if the 'changeType' field has been set, false otherwise.
      */
    public boolean hasChangeType() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'changeType' field.
      * @return This builder.
      */
    public com.project.young.kafka.product.avro.model.ProductCatalogChangedAvroModel.Builder clearChangeType() {
      changeType = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'occurredAt' field.
      * @return The value.
      */
    public long getOccurredAt() {
      return occurredAt;
    }


    /**
      * Sets the value of the 'occurredAt' field.
      * @param value The value of 'occurredAt'.
      * @return This builder.
      */
    public com.project.young.kafka.product.avro.model.ProductCatalogChangedAvroModel.Builder setOccurredAt(long value) {
      validate(fields()[4], value);
      this.occurredAt = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'occurredAt' field has been set.
      * @return True if the 'occurredAt' field has been set, false otherwise.
      */
    public boolean hasOccurredAt() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'occurredAt' field.
      * @return This builder.
      */
    public com.project.young.kafka.product.avro.model.ProductCatalogChangedAvroModel.Builder clearOccurredAt() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ProductCatalogChangedAvroModel build() {
      try {
        ProductCatalogChangedAvroModel record = new ProductCatalogChangedAvroModel();
        record.eventId = fieldSetFlags()[0] ? this.eventId : (java.lang.String) defaultValue(fields()[0]);
        record.productId = fieldSetFlags()[1] ? this.productId : (java.lang.String) defaultValue(fields()[1]);
        record.categoryId = fieldSetFlags()[2] ? this.categoryId : (java.lang.Long) defaultValue(fields()[2]);
        record.changeType = fieldSetFlags()[3] ? this.changeType : (java.lang.String) defaultValue(fields()[3]);
        record.occurredAt = fieldSetFlags()[4] ? this.occurredAt : (java.lang.Long) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ProductCatalogChangedAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<ProductCatalogChangedAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ProductCatalogChangedAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<ProductCatalogChangedAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.eventId);

    out.writeString(this.productId);

    if (this.categoryId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.categoryId);
    }

    out.writeString(this.changeType);

    out.writeLong(this.occurredAt);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.eventId = in.readString();

      this.productId = in.readString();

      if (in.readIndex() != 1) {
        in.readNull();
        this.categoryId = null;
      } else {
        this.categoryId = in.readLong();
      }

      this.changeType = in.readString();

      this.occurredAt = in.readLong();

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.eventId = in.readString();
          break;

        case 1:
          this.productId = in.readString();
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.categoryId = null;
          } else {
            this.categoryId = in.readLong();
          }
          break;

        case 3:
          this.changeType = in.readString();
          break;

        case 4:
          this.occurredAt = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










