/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.project.young.kafka.payment.avro.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Emitted when payment fails. Triggers order cancellation and inventory release. */
@org.apache.avro.specific.AvroGenerated
public class PaymentFailedAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1876864128594358135L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PaymentFailedAvroModel\",\"namespace\":\"com.project.young.kafka.payment.avro.model\",\"doc\":\"Emitted when payment fails. Triggers order cancellation and inventory release.\",\"fields\":[{\"name\":\"eventId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"paymentId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"orderId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"userId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"amount\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"failureReason\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"occurredAt\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PaymentFailedAvroModel> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PaymentFailedAvroModel> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PaymentFailedAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PaymentFailedAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PaymentFailedAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PaymentFailedAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PaymentFailedAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PaymentFailedAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PaymentFailedAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String eventId;
  private java.lang.String paymentId;
  private java.lang.String orderId;
  private java.lang.String userId;
  private java.lang.String amount;
  private java.lang.String failureReason;
  private long occurredAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PaymentFailedAvroModel() {}

  /**
   * All-args constructor.
   * @param eventId The new value for eventId
   * @param paymentId The new value for paymentId
   * @param orderId The new value for orderId
   * @param userId The new value for userId
   * @param amount The new value for amount
   * @param failureReason The new value for failureReason
   * @param occurredAt The new value for occurredAt
   */
  public PaymentFailedAvroModel(java.lang.String eventId, java.lang.String paymentId, java.lang.String orderId, java.lang.String userId, java.lang.String amount, java.lang.String failureReason, java.lang.Long occurredAt) {
    this.eventId = eventId;
    this.paymentId = paymentId;
    this.orderId = orderId;
    this.userId = userId;
    this.amount = amount;
    this.failureReason = failureReason;
    this.occurredAt = occurredAt;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return eventId;
    case 1: return paymentId;
    case 2: return orderId;
    case 3: return userId;
    case 4: return amount;
    case 5: return failureReason;
    case 6: return occurredAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: eventId = value$ != null ? value$.toString() : null; break;
    case 1: paymentId = value$ != null ? value$.toString() : null; break;
    case 2: orderId = value$ != null ? value$.toString() : null; break;
    case 3: userId = value$ != null ? value$.toString() : null; break;
    case 4: amount = value$ != null ? value$.toString() : null; break;
    case 5: failureReason = value$ != null ? value$.toString() : null; break;
    case 6: occurredAt = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'eventId' field.
   * @return The value of the 'eventId' field.
   */
  public java.lang.String getEventId() {
    return eventId;
  }


  /**
   * Sets the value of the 'eventId' field.
   * @param value the value to set.
   */
  public void setEventId(java.lang.String value) {
    this.eventId = value;
  }

  /**
   * Gets the value of the 'paymentId' field.
   * @return The value of the 'paymentId' field.
   */
  public java.lang.String getPaymentId() {
    return paymentId;
  }


  /**
   * Sets the value of the 'paymentId' field.
   * @param value the value to set.
   */
  public void setPaymentId(java.lang.String value) {
    this.paymentId = value;
  }

  /**
   * Gets the value of the 'orderId' field.
   * @return The value of the 'orderId' field.
   */
  public java.lang.String getOrderId() {
    return orderId;
  }


  /**
   * Sets the value of the 'orderId' field.
   * @param value the value to set.
   */
  public void setOrderId(java.lang.String value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public java.lang.String getUserId() {
    return userId;
  }


  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.String value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'amount' field.
   * @return The value of the 'amount' field.
   */
  public java.lang.String getAmount() {
    return amount;
  }


  /**
   * Sets the value of the 'amount' field.
   * @param value the value to set.
   */
  public void setAmount(java.lang.String value) {
    this.amount = value;
  }

  /**
   * Gets the value of the 'failureReason' field.
   * @return The value of the 'failureReason' field.
   */
  public java.lang.String getFailureReason() {
    return failureReason;
  }


  /**
   * Sets the value of the 'failureReason' field.
   * @param value the value to set.
   */
  public void setFailureReason(java.lang.String value) {
    this.failureReason = value;
  }

  /**
   * Gets the value of the 'occurredAt' field.
   * @return The value of the 'occurredAt' field.
   */
  public long getOccurredAt() {
    return occurredAt;
  }


  /**
   * Sets the value of the 'occurredAt' field.
   * @param value the value to set.
   */
  public void setOccurredAt(long value) {
    this.occurredAt = value;
  }

  /**
   * Creates a new PaymentFailedAvroModel RecordBuilder.
   * @return A new PaymentFailedAvroModel RecordBuilder
   */
  public static com.project.young.kafka.payment.avro.model.PaymentFailedAvroModel.Builder newBuilder() {
    return new com.project.young.kafka.payment.avro.model.PaymentFailedAvroModel.Builder();
  }

  /**
   * Creates a new PaymentFailedAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PaymentFailedAvroModel RecordBuilder
   */
  public static com.project.young.kafka.payment.avro.model.PaymentFailedAvroModel.Builder newBuilder(com.project.young.kafka.payment.avro.model.PaymentFailedAvroModel.Builder other) {
    if (other == null) {
      return new com.project.young.kafka.payment.avro.model.PaymentFailedAvroModel.Builder();
    } else {
      return new com.project.young.kafka.payment.avro.model.PaymentFailedAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new PaymentFailedAvroModel RecordBuilder by copying an existing PaymentFailedAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new PaymentFailedAvroModel RecordBuilder
   */
  public static com.project.young.kafka.payment.avro.model.PaymentFailedAvroModel.Builder newBuilder(com.project.young.kafka.payment.avro.model.PaymentFailedAvroModel other) {
    if (other == null) {
      return new com.project.young.kafka.payment.avro.model.PaymentFailedAvroModel.Builder();
    } else {
      return new com.project.young.kafka.payment.avro.model.PaymentFailedAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for PaymentFailedAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PaymentFailedAvroModel>
    implements org.apache.avro.data.RecordBuilder<PaymentFailedAvroModel> {

    private java.lang.String eventId;
    private java.lang.String paymentId;
    private java.lang.String orderId;
    private java.lang.String userId;
    private java.lang.String amount;
    private java.lang.String failureReason;
    private long occurredAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.project.young.kafka.payment.avro.model.PaymentFailedAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.paymentId)) {
        this.paymentId = data().deepCopy(fields()[1].schema(), other.paymentId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.orderId)) {
        this.orderId = data().deepCopy(fields()[2].schema(), other.orderId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.userId)) {
        this.userId = data().deepCopy(fields()[3].schema(), other.userId);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.amount)) {
        this.amount = data().deepCopy(fields()[4].schema(), other.amount);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.failureReason)) {
        this.failureReason = data().deepCopy(fields()[5].schema(), other.failureReason);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.occurredAt)) {
        this.occurredAt = data().deepCopy(fields()[6].schema(), other.occurredAt);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing PaymentFailedAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.project.young.kafka.payment.avro.model.PaymentFailedAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.paymentId)) {
        this.paymentId = data().deepCopy(fields()[1].schema(), other.paymentId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.orderId)) {
        this.orderId = data().deepCopy(fields()[2].schema(), other.orderId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.userId)) {
        this.userId = data().deepCopy(fields()[3].schema(), other.userId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.amount)) {
        this.amount = data().deepCopy(fields()[4].schema(), other.amount);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.failureReason)) {
        this.failureReason = data().deepCopy(fields()[5].schema(), other.failureReason);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.occurredAt)) {
        this.occurredAt = data().deepCopy(fields()[6].schema(), other.occurredAt);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'eventId' field.
      * @return The value.
      */
    public java.lang.String getEventId() {
      return eventId;
    }


    /**
      * Sets the value of the 'eventId' field.
      * @param value The value of 'eventId'.
      * @return This builder.
      */
    public com.project.young.kafka.payment.avro.model.PaymentFailedAvroModel.Builder setEventId(java.lang.String value) {
      validate(fields()[0], value);
      this.eventId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'eventId' field has been set.
      * @return True if the 'eventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'eventId' field.
      * @return This builder.
      */
    public com.project.young.kafka.payment.avro.model.PaymentFailedAvroModel.Builder clearEventId() {
      eventId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'paymentId' field.
      * @return The value.
      */
    public java.lang.String getPaymentId() {
      return paymentId;
    }


    /**
      * Sets the value of the 'paymentId' field.
      * @param value The value of 'paymentId'.
      * @return This builder.
      */
    public com.project.young.kafka.payment.avro.model.PaymentFailedAvroModel.Builder setPaymentId(java.lang.String value) {
      validate(fields()[1], value);
      this.paymentId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'paymentId' field has been set.
      * @return True if the 'paymentId' field has been set, false otherwise.
      */
    public boolean hasPaymentId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'paymentId' field.
      * @return This builder.
      */
    public com.project.young.kafka.payment.avro.model.PaymentFailedAvroModel.Builder clearPaymentId() {
      paymentId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderId' field.
      * @return The value.
      */
    public java.lang.String getOrderId() {
      return orderId;
    }


    /**
      * Sets the value of the 'orderId' field.
      * @param value The value of 'orderId'.
      * @return This builder.
      */
    public com.project.young.kafka.payment.avro.model.PaymentFailedAvroModel.Builder setOrderId(java.lang.String value) {
      validate(fields()[2], value);
      this.orderId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'orderId' field has been set.
      * @return True if the 'orderId' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'orderId' field.
      * @return This builder.
      */
    public com.project.young.kafka.payment.avro.model.PaymentFailedAvroModel.Builder clearOrderId() {
      orderId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public java.lang.String getUserId() {
      return userId;
    }


    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public com.project.young.kafka.payment.avro.model.PaymentFailedAvroModel.Builder setUserId(java.lang.String value) {
      validate(fields()[3], value);
      this.userId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public com.project.young.kafka.payment.avro.model.PaymentFailedAvroModel.Builder clearUserId() {
      userId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'amount' field.
      * @return The value.
      */
    public java.lang.String getAmount() {
      return amount;
    }


    /**
      * Sets the value of the 'amount' field.
      * @param value The value of 'amount'.
      * @return This builder.
      */
    public com.project.young.kafka.payment.avro.model.PaymentFailedAvroModel.Builder setAmount(java.lang.String value) {
      validate(fields()[4], value);
      this.amount = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'amount' field has been set.
      * @return True if the 'amount' field has been set, false otherwise.
      */
    public boolean hasAmount() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'amount' field.
      * @return This builder.
      */
    public com.project.young.kafka.payment.avro.model.PaymentFailedAvroModel.Builder clearAmount() {
      amount = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'failureReason' field.
      * @return The value.
      */
    public java.lang.String getFailureReason() {
      return failureReason;
    }


    /**
      * Sets the value of the 'failureReason' field.
      * @param value The value of 'failureReason'.
      * @return This builder.
      */
    public com.project.young.kafka.payment.avro.model.PaymentFailedAvroModel.Builder setFailureReason(java.lang.String value) {
      validate(fields()[5], value);
      this.failureReason = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'failureReason' field has been set.
      * @return True if the 'failureReason' field has been set, false otherwise.
      */
    public boolean hasFailureReason() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'failureReason' field.
      * @return This builder.
      */
    public com.project.young.kafka.payment.avro.model.PaymentFailedAvroModel.Builder clearFailureReason() {
      failureReason = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'occurredAt' field.
      * @return The value.
      */
    public long getOccurredAt() {
      return occurredAt;
    }


    /**
      * Sets the value of the 'occurredAt' field.
      * @param value The value of 'occurredAt'.
      * @return This builder.
      */
    public com.project.young.kafka.payment.avro.model.PaymentFailedAvroModel.Builder setOccurredAt(long value) {
      validate(fields()[6], value);
      this.occurredAt = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'occurredAt' field has been set.
      * @return True if the 'occurredAt' field has been set, false otherwise.
      */
    public boolean hasOccurredAt() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'occurredAt' field.
      * @return This builder.
      */
    public com.project.young.kafka.payment.avro.model.PaymentFailedAvroModel.Builder clearOccurredAt() {
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PaymentFailedAvroModel build() {
      try {
        PaymentFailedAvroModel record = new PaymentFailedAvroModel();
        record.eventId = fieldSetFlags()[0] ? this.eventId : (java.lang.String) defaultValue(fields()[0]);
        record.paymentId = fieldSetFlags()[1] ? this.paymentId : (java.lang.String) defaultValue(fields()[1]);
        record.orderId = fieldSetFlags()[2] ? this.orderId : (java.lang.String) defaultValue(fields()[2]);
        record.userId = fieldSetFlags()[3] ? this.userId : (java.lang.String) defaultValue(fields()[3]);
        record.amount = fieldSetFlags()[4] ? this.amount : (java.lang.String) defaultValue(fields()[4]);
        record.failureReason = fieldSetFlags()[5] ? this.failureReason : (java.lang.String) defaultValue(fields()[5]);
        record.occurredAt = fieldSetFlags()[6] ? this.occurredAt : (java.lang.Long) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PaymentFailedAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<PaymentFailedAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PaymentFailedAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<PaymentFailedAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.eventId);

    out.writeString(this.paymentId);

    out.writeString(this.orderId);

    out.writeString(this.userId);

    out.writeString(this.amount);

    out.writeString(this.failureReason);

    out.writeLong(this.occurredAt);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.eventId = in.readString();

      this.paymentId = in.readString();

      this.orderId = in.readString();

      this.userId = in.readString();

      this.amount = in.readString();

      this.failureReason = in.readString();

      this.occurredAt = in.readLong();

    } else {
      for (int i = 0; i < 7; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.eventId = in.readString();
          break;

        case 1:
          this.paymentId = in.readString();
          break;

        case 2:
          this.orderId = in.readString();
          break;

        case 3:
          this.userId = in.readString();
          break;

        case 4:
          this.amount = in.readString();
          break;

        case 5:
          this.failureReason = in.readString();
          break;

        case 6:
          this.occurredAt = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










