/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.project.young.kafka.order.avro.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Emitted after order placement (PENDING_PAYMENT). Mirrors orders.order_outbox row for polling relay. */
@org.apache.avro.specific.AvroGenerated
public class OrderCreatedAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1948279978252675152L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OrderCreatedAvroModel\",\"namespace\":\"com.project.young.kafka.order.avro.model\",\"doc\":\"Emitted after order placement (PENDING_PAYMENT). Mirrors orders.order_outbox row for polling relay.\",\"fields\":[{\"name\":\"eventId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"orderId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"userId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"totalAmount\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Decimal string, same as Debezium decimal.handling.mode=string\"},{\"name\":\"currency\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":\"KRW\"},{\"name\":\"occurredAt\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OrderCreatedAvroModel> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OrderCreatedAvroModel> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<OrderCreatedAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<OrderCreatedAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<OrderCreatedAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this OrderCreatedAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a OrderCreatedAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a OrderCreatedAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static OrderCreatedAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String eventId;
  private java.lang.String orderId;
  private java.lang.String userId;
  /** Decimal string, same as Debezium decimal.handling.mode=string */
  private java.lang.String totalAmount;
  private java.lang.String currency;
  private long occurredAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OrderCreatedAvroModel() {}

  /**
   * All-args constructor.
   * @param eventId The new value for eventId
   * @param orderId The new value for orderId
   * @param userId The new value for userId
   * @param totalAmount Decimal string, same as Debezium decimal.handling.mode=string
   * @param currency The new value for currency
   * @param occurredAt The new value for occurredAt
   */
  public OrderCreatedAvroModel(java.lang.String eventId, java.lang.String orderId, java.lang.String userId, java.lang.String totalAmount, java.lang.String currency, java.lang.Long occurredAt) {
    this.eventId = eventId;
    this.orderId = orderId;
    this.userId = userId;
    this.totalAmount = totalAmount;
    this.currency = currency;
    this.occurredAt = occurredAt;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return eventId;
    case 1: return orderId;
    case 2: return userId;
    case 3: return totalAmount;
    case 4: return currency;
    case 5: return occurredAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: eventId = value$ != null ? value$.toString() : null; break;
    case 1: orderId = value$ != null ? value$.toString() : null; break;
    case 2: userId = value$ != null ? value$.toString() : null; break;
    case 3: totalAmount = value$ != null ? value$.toString() : null; break;
    case 4: currency = value$ != null ? value$.toString() : null; break;
    case 5: occurredAt = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'eventId' field.
   * @return The value of the 'eventId' field.
   */
  public java.lang.String getEventId() {
    return eventId;
  }


  /**
   * Sets the value of the 'eventId' field.
   * @param value the value to set.
   */
  public void setEventId(java.lang.String value) {
    this.eventId = value;
  }

  /**
   * Gets the value of the 'orderId' field.
   * @return The value of the 'orderId' field.
   */
  public java.lang.String getOrderId() {
    return orderId;
  }


  /**
   * Sets the value of the 'orderId' field.
   * @param value the value to set.
   */
  public void setOrderId(java.lang.String value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public java.lang.String getUserId() {
    return userId;
  }


  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.String value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'totalAmount' field.
   * @return Decimal string, same as Debezium decimal.handling.mode=string
   */
  public java.lang.String getTotalAmount() {
    return totalAmount;
  }


  /**
   * Sets the value of the 'totalAmount' field.
   * Decimal string, same as Debezium decimal.handling.mode=string
   * @param value the value to set.
   */
  public void setTotalAmount(java.lang.String value) {
    this.totalAmount = value;
  }

  /**
   * Gets the value of the 'currency' field.
   * @return The value of the 'currency' field.
   */
  public java.lang.String getCurrency() {
    return currency;
  }


  /**
   * Sets the value of the 'currency' field.
   * @param value the value to set.
   */
  public void setCurrency(java.lang.String value) {
    this.currency = value;
  }

  /**
   * Gets the value of the 'occurredAt' field.
   * @return The value of the 'occurredAt' field.
   */
  public long getOccurredAt() {
    return occurredAt;
  }


  /**
   * Sets the value of the 'occurredAt' field.
   * @param value the value to set.
   */
  public void setOccurredAt(long value) {
    this.occurredAt = value;
  }

  /**
   * Creates a new OrderCreatedAvroModel RecordBuilder.
   * @return A new OrderCreatedAvroModel RecordBuilder
   */
  public static com.project.young.kafka.order.avro.model.OrderCreatedAvroModel.Builder newBuilder() {
    return new com.project.young.kafka.order.avro.model.OrderCreatedAvroModel.Builder();
  }

  /**
   * Creates a new OrderCreatedAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OrderCreatedAvroModel RecordBuilder
   */
  public static com.project.young.kafka.order.avro.model.OrderCreatedAvroModel.Builder newBuilder(com.project.young.kafka.order.avro.model.OrderCreatedAvroModel.Builder other) {
    if (other == null) {
      return new com.project.young.kafka.order.avro.model.OrderCreatedAvroModel.Builder();
    } else {
      return new com.project.young.kafka.order.avro.model.OrderCreatedAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new OrderCreatedAvroModel RecordBuilder by copying an existing OrderCreatedAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new OrderCreatedAvroModel RecordBuilder
   */
  public static com.project.young.kafka.order.avro.model.OrderCreatedAvroModel.Builder newBuilder(com.project.young.kafka.order.avro.model.OrderCreatedAvroModel other) {
    if (other == null) {
      return new com.project.young.kafka.order.avro.model.OrderCreatedAvroModel.Builder();
    } else {
      return new com.project.young.kafka.order.avro.model.OrderCreatedAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for OrderCreatedAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OrderCreatedAvroModel>
    implements org.apache.avro.data.RecordBuilder<OrderCreatedAvroModel> {

    private java.lang.String eventId;
    private java.lang.String orderId;
    private java.lang.String userId;
    /** Decimal string, same as Debezium decimal.handling.mode=string */
    private java.lang.String totalAmount;
    private java.lang.String currency;
    private long occurredAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.project.young.kafka.order.avro.model.OrderCreatedAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.orderId)) {
        this.orderId = data().deepCopy(fields()[1].schema(), other.orderId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.userId)) {
        this.userId = data().deepCopy(fields()[2].schema(), other.userId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.totalAmount)) {
        this.totalAmount = data().deepCopy(fields()[3].schema(), other.totalAmount);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.currency)) {
        this.currency = data().deepCopy(fields()[4].schema(), other.currency);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.occurredAt)) {
        this.occurredAt = data().deepCopy(fields()[5].schema(), other.occurredAt);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing OrderCreatedAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.project.young.kafka.order.avro.model.OrderCreatedAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.orderId)) {
        this.orderId = data().deepCopy(fields()[1].schema(), other.orderId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.userId)) {
        this.userId = data().deepCopy(fields()[2].schema(), other.userId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.totalAmount)) {
        this.totalAmount = data().deepCopy(fields()[3].schema(), other.totalAmount);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.currency)) {
        this.currency = data().deepCopy(fields()[4].schema(), other.currency);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.occurredAt)) {
        this.occurredAt = data().deepCopy(fields()[5].schema(), other.occurredAt);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'eventId' field.
      * @return The value.
      */
    public java.lang.String getEventId() {
      return eventId;
    }


    /**
      * Sets the value of the 'eventId' field.
      * @param value The value of 'eventId'.
      * @return This builder.
      */
    public com.project.young.kafka.order.avro.model.OrderCreatedAvroModel.Builder setEventId(java.lang.String value) {
      validate(fields()[0], value);
      this.eventId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'eventId' field has been set.
      * @return True if the 'eventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'eventId' field.
      * @return This builder.
      */
    public com.project.young.kafka.order.avro.model.OrderCreatedAvroModel.Builder clearEventId() {
      eventId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderId' field.
      * @return The value.
      */
    public java.lang.String getOrderId() {
      return orderId;
    }


    /**
      * Sets the value of the 'orderId' field.
      * @param value The value of 'orderId'.
      * @return This builder.
      */
    public com.project.young.kafka.order.avro.model.OrderCreatedAvroModel.Builder setOrderId(java.lang.String value) {
      validate(fields()[1], value);
      this.orderId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'orderId' field has been set.
      * @return True if the 'orderId' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'orderId' field.
      * @return This builder.
      */
    public com.project.young.kafka.order.avro.model.OrderCreatedAvroModel.Builder clearOrderId() {
      orderId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public java.lang.String getUserId() {
      return userId;
    }


    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public com.project.young.kafka.order.avro.model.OrderCreatedAvroModel.Builder setUserId(java.lang.String value) {
      validate(fields()[2], value);
      this.userId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public com.project.young.kafka.order.avro.model.OrderCreatedAvroModel.Builder clearUserId() {
      userId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'totalAmount' field.
      * Decimal string, same as Debezium decimal.handling.mode=string
      * @return The value.
      */
    public java.lang.String getTotalAmount() {
      return totalAmount;
    }


    /**
      * Sets the value of the 'totalAmount' field.
      * Decimal string, same as Debezium decimal.handling.mode=string
      * @param value The value of 'totalAmount'.
      * @return This builder.
      */
    public com.project.young.kafka.order.avro.model.OrderCreatedAvroModel.Builder setTotalAmount(java.lang.String value) {
      validate(fields()[3], value);
      this.totalAmount = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'totalAmount' field has been set.
      * Decimal string, same as Debezium decimal.handling.mode=string
      * @return True if the 'totalAmount' field has been set, false otherwise.
      */
    public boolean hasTotalAmount() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'totalAmount' field.
      * Decimal string, same as Debezium decimal.handling.mode=string
      * @return This builder.
      */
    public com.project.young.kafka.order.avro.model.OrderCreatedAvroModel.Builder clearTotalAmount() {
      totalAmount = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'currency' field.
      * @return The value.
      */
    public java.lang.String getCurrency() {
      return currency;
    }


    /**
      * Sets the value of the 'currency' field.
      * @param value The value of 'currency'.
      * @return This builder.
      */
    public com.project.young.kafka.order.avro.model.OrderCreatedAvroModel.Builder setCurrency(java.lang.String value) {
      validate(fields()[4], value);
      this.currency = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'currency' field has been set.
      * @return True if the 'currency' field has been set, false otherwise.
      */
    public boolean hasCurrency() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'currency' field.
      * @return This builder.
      */
    public com.project.young.kafka.order.avro.model.OrderCreatedAvroModel.Builder clearCurrency() {
      currency = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'occurredAt' field.
      * @return The value.
      */
    public long getOccurredAt() {
      return occurredAt;
    }


    /**
      * Sets the value of the 'occurredAt' field.
      * @param value The value of 'occurredAt'.
      * @return This builder.
      */
    public com.project.young.kafka.order.avro.model.OrderCreatedAvroModel.Builder setOccurredAt(long value) {
      validate(fields()[5], value);
      this.occurredAt = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'occurredAt' field has been set.
      * @return True if the 'occurredAt' field has been set, false otherwise.
      */
    public boolean hasOccurredAt() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'occurredAt' field.
      * @return This builder.
      */
    public com.project.young.kafka.order.avro.model.OrderCreatedAvroModel.Builder clearOccurredAt() {
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OrderCreatedAvroModel build() {
      try {
        OrderCreatedAvroModel record = new OrderCreatedAvroModel();
        record.eventId = fieldSetFlags()[0] ? this.eventId : (java.lang.String) defaultValue(fields()[0]);
        record.orderId = fieldSetFlags()[1] ? this.orderId : (java.lang.String) defaultValue(fields()[1]);
        record.userId = fieldSetFlags()[2] ? this.userId : (java.lang.String) defaultValue(fields()[2]);
        record.totalAmount = fieldSetFlags()[3] ? this.totalAmount : (java.lang.String) defaultValue(fields()[3]);
        record.currency = fieldSetFlags()[4] ? this.currency : (java.lang.String) defaultValue(fields()[4]);
        record.occurredAt = fieldSetFlags()[5] ? this.occurredAt : (java.lang.Long) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OrderCreatedAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<OrderCreatedAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OrderCreatedAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<OrderCreatedAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.eventId);

    out.writeString(this.orderId);

    out.writeString(this.userId);

    out.writeString(this.totalAmount);

    out.writeString(this.currency);

    out.writeLong(this.occurredAt);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.eventId = in.readString();

      this.orderId = in.readString();

      this.userId = in.readString();

      this.totalAmount = in.readString();

      this.currency = in.readString();

      this.occurredAt = in.readLong();

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.eventId = in.readString();
          break;

        case 1:
          this.orderId = in.readString();
          break;

        case 2:
          this.userId = in.readString();
          break;

        case 3:
          this.totalAmount = in.readString();
          break;

        case 4:
          this.currency = in.readString();
          break;

        case 5:
          this.occurredAt = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










